/* ───────────────────────────────────────────
   Branding — Report headers, footers, logos
   ─────────────────────────────────────────── */

import { BRANDING } from "@/config/constants";
import type { PageOptions, SignatureOptions } from "@/types";
import { escapeHtml, todayFormatted } from "./utils";

/** Company branding block for reports */
export function generateLogoBlock(): string {
  const logo = BRANDING.logoUrl
    ? `<img src="${escapeHtml(BRANDING.logoUrl)}" alt="Logo" style="max-height:60px;max-width:120px;" />`
    : `<div style="font-size:2rem;font-weight:700;color:var(--primary,#0056b3);">${escapeHtml(BRANDING.companyName)}</div>`;

  return `
    <div style="display:flex;align-items:center;gap:1rem;margin-bottom:0.5rem;">
      ${logo}
      <div>
        <div style="font-size:1.1rem;font-weight:700;">${escapeHtml(BRANDING.companyName)}</div>
        <div style="font-size:0.8rem;color:var(--muted,#6c757d);">${escapeHtml(BRANDING.address)}</div>
        <div style="font-size:0.8rem;color:var(--muted,#6c757d);">
          Tel: ${escapeHtml(BRANDING.phone1)} | Email: ${escapeHtml(BRANDING.email)}
        </div>
        <div style="font-size:0.75rem;color:var(--muted,#6c757d);">RC: ${escapeHtml(BRANDING.rcNumber)}</div>
      </div>
    </div>
    <hr style="border:none;border-top:2px solid var(--primary,#0056b3);margin:0.5rem 0;" />
  `;
}

/** Unified page footer for printed reports */
export function generateUnifiedFooter(): string {
  return `
    <div style="margin-top:1.5rem;border-top:1px solid #ddd;padding-top:0.5rem;font-size:0.7rem;color:#666;text-align:center;">
      ${escapeHtml(BRANDING.companyName)} &middot; ${escapeHtml(BRANDING.address)} &middot; ${escapeHtml(BRANDING.phone1)}<br/>
      Generated by FieldScan Pro on ${todayFormatted()}
    </div>
  `;
}

/** Signature block for reports */
export function generateUnifiedSignatureBlock(options?: SignatureOptions): string {
  const name = options?.name || BRANDING.companyName;
  const signImage = options?.signImage || "";
  const date = options?.date || todayFormatted();

  return `
    <div style="margin-top:2rem;display:flex;justify-content:space-between;align-items:flex-end;">
      <div style="text-align:center;">
        ${signImage ? `<img src="${escapeHtml(signImage)}" style="max-height:50px;" /><br/>` : ""}
        <div style="border-top:1px solid #333;width:200px;margin:0.5rem auto 0.2rem;"></div>
        <div style="font-size:0.8rem;font-weight:600;">${escapeHtml(name)}</div>
        <div style="font-size:0.7rem;color:#666;">Date: ${escapeHtml(date)}</div>
      </div>
    </div>
  `;
}

/** Wrap report body with full header/footer/page shell */
export function wrapUnifiedPage(
  bodyContent: string,
  options: PageOptions = {}
): string {
  const title = options.title || "Report";
  const subtitle = options.subtitle || "";
  const date = options.date || todayFormatted();

  return `
    <div style="font-family:Inter,sans-serif;font-size:0.85rem;line-height:1.5;color:#1a1a1a;max-width:900px;margin:0 auto;padding:1rem;">
      ${generateLogoBlock()}
      <div style="text-align:center;margin-bottom:1rem;">
        <div style="font-size:1.2rem;font-weight:700;">${escapeHtml(title)}</div>
        ${subtitle ? `<div style="font-size:0.9rem;color:#555;">${escapeHtml(subtitle)}</div>` : ""}
        <div style="font-size:0.8rem;color:#888;">${escapeHtml(date)}</div>
      </div>
      ${bodyContent}
      ${options.signature ? generateUnifiedSignatureBlock(options.signature) : ""}
      ${options.hideFooter ? "" : generateUnifiedFooter()}
    </div>
  `;
}

/* ─── Simplified helpers for inline use ─── */

export function getReportHeader(title: string): string {
  return generateLogoBlock() +
    `<div style="text-align:center;margin:0.5rem 0 1rem;">
      <div style="font-size:1.1rem;font-weight:700;">${escapeHtml(title)}</div>
    </div>`;
}

export function getReportFooter(): string {
  return generateUnifiedFooter();
}
